mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 3001
  env: release
site_info:
  created_at: "2024-01-01"
  bei_an: 皖ICP备2022012261号-2
  title: 与蜗牛漫步
  qq_image: /uploads/file/Gopher/qq_20240108221653.jpg
  version: 2.0.0
  email: 2112025700@qq.com
  wechat_image: /uploads/file/Gopher/wechat_20240108221659.jpg
  name: 与蜗牛漫步
  job: 全栈开发
  addr: 中国重庆
  slogan: 个人博客
  slogan_en: GOPHERBLOG
  web: http://blog.weijia-top/
  csdn_url: https://woniu.blog.csdn.net/
  gitee_url: https://gitee.com/wei_jia0826
  github_url: https://github.com/qweijiaq
upload:
  size: 6
  path: uploads/file
qq:
  app_id: "102088326"
  key: eCXfaIl04uU8ZmkV
  redirect: http://blog.wei-jia.top/oauth?flag=qq
qi_niu:
  enable: true
  access_key: 20XGZQLc3G3qBbuKm_7ryQ4h3nlGCxU2mvGkwiJF
  secret_key: 7S6gKqTOHUjg9TjOy-QKwMIQlIqjSEwiyHKFwXkm
  bucket: emlog-img
  cdn: http://qiniu.wei-jia.top/
  zone: z2
  prefix: GopherBlog
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: 2112025700@qq.com
  password: qfbftrvsymwabfje
  default_from_email: GopherBlog
  use_ssl: true
  user_tls: false
jwt:
  secret: '******'
  expires: 240
  issuer: weijia
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  isAnonymous: true
  isShowTime: false
  defaultLimit: 50
  contentLength: 101
  welcomeTitle: 在线聊天室
  isOnlinePeople: true
  isSendImage: true
  isSendFile: true
  isMd: true
gaode:
  enable: true
  key: cdfabcac56fd9f6e2a9319d996ec0a3e
big_model:
  setting:
    name: "生效大模型的名称" # eg. qwen -> 通义千问
    enable: true # 是否启用
    api_key: "xxxxx"
    api_secret: "xxxxx"
    title: GopherModel
    prompt: "" # 加强提示词
    slogan: "让更多人用上大模型"
  model_list:
    - label: 通义千问
      value: qwen
      disable: false
    - label: 文心一言
      value: wenxin
      disable: true
    - label: 星火大模型
      value: xinhuo
      disable: true
    - label: 天工大模型
      value: tiangong
      disable: true
    - label: ChatGPT
      value: chatgpt
      disable: true
  session_setting: # 会话
    chat_scope:
    session_scope:
    day_scope:

